device/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'device'
urlpatterns = [
   path("",views.HomePage.as_view(),name="home"),
   path("getlist/",views.GetList.as_view(),name="getlist")
]

farmos/urls.py
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("device.urls"),name='device')
]

device/models.py
from django.db import models

# Create your models here.

device/views.py
import json

from django.shortcuts import render
from django.views import View
import requests
from django.conf import settings
# Create your views here.


class HomePage(View):

    def get(self,request):

        ctx = {}
        return render(request,"device/home.html",ctx)

    def post(self,request):
        try:
            data = request.POST.get('textarea1',None)
            response = requests.post(settings.API_HIT,json.dumps(data))
            if response.status_code==200:
                ctx = {"message":"succesfully added","error":False}
                return render(request,"device/home.html",ctx)
            response = json.loads(response.content)
            ctx = {'message':str(response),"error":True}
            return render(request, "device/home.html", ctx)
        except Exception as e:
            ctx = {'message': str(e), "error": True}
            return render(request, "device/home.html", ctx)


class GetList(View):

    def get(self,request):


        try:
            response =requests.get(url=settings.GET_API)
            if response.status_code==200:
                list_objs = json.loads(response.content)
                ctx = {'list_objs':list_objs}
                return render(request,"device/home.html",ctx)
            response = json.loads(response.content)
            ctx = {'message':str(response),'error':True}
            return render(request,'device/home.html',ctx)
        except Exception as e:
            ctx = {'message': str(e), "error": True}
            return render(request, "device/home.html", ctx)

device/templates/device/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
<br>
<br>
<div class="container">

    {% if error %}
    <div class="alert alert-danger" role="alert">
  {{message}}
    </div>

    {% else %}

    <div class="alert alert-success" role="alert">
  {{message}}
</div>

    {% endif %}

    <div class="row">
        <form method="post" action="{% url 'device:home' %}">
            {% csrf_token %}
  <div class="mb-3">
    <label for="textarea1" class="form-label">Payload</label>
    <textarea id="textarea1" name="textarea1" class="form-control" rows="4" cols="50">
</textarea>
    <div id="emailHelp" class="form-text">ENTER JSON</div>
  </div>

  <button type="submit" class="btn btn-primary">Submit</button>
</form>
    </div>


    <br><br>
    <hr>
    <form method="get" action="{% url 'device:getlist' %}">

        <button type="submit" class="btn btn-primary">GET LIST</button>

    </form>

<br>

    {% if list_objs %}
        {% for i in list_objs %}
        <p>
            {{i}}<br></p>
        {% endfor %}

    {% endif %}

</div>


</body>
</html>